---
sidebar: sidebar 
permalink: alerts-faq.html 
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert 
summary: 質問に対する簡単な回答を探している場合は、このNetAppアラートの FAQ が役立ちます。 
---
= NetAppアラートに関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、 NetAppアラートに関する質問への簡単な回答を探している場合に役立ちます。



== NetAppアラートへのアクセス

* NetAppアラートの URL とは何ですか?*  URL については、ブラウザで次のように入力します。 https://console.netapp.com/["https://console.netapp.com/"^] NetApp Consoleにアクセスします。

* NetAppアラートを使用するにはライセンスが必要ですか?*

NetAppアラートを使用するには、 NetApp ONTAP 9.10 以上のライセンスが必要です。ライセンスをNetApp Consoleのデジタル ウォレットに入力する必要はありません。

NetAppアラートの試用ライセンスは必要ありません。

* NetAppアラートを有効にするにはどうすればいいですか?* NetAppアラートを有効にする必要はありません。アラート オプションは、NetApp Consoleの左側のナビゲーションで自動的に有効になります。

まず、コンソール エージェントを使用すると、 NetAppアラートに適切な機能が含まれます。

** NetAppアラートは標準モード、制限モード、プライベート モードで利用できますか?**  NetAppアラートは、NetApp Console標準 (パブリック) にのみ展開できます。

NetApp Consoleサービス全体にわたるこれらのモードの説明については、 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["NetApp Consoleの展開モード"^] 。

**アクセス権限はどのように処理されますか?**  NetApp Console組織管理者だけが、 NetAppアラートを開始し、ワークロードを検出できます (これにはリソースの使用をコミットする必要があるため)。

アラートは、NetApp Console組織内のクラスターのリソースへのアクセスに応じて、ログインしているユーザーに表示されます。



== アラートを表示

**アラートを受信し始めるまでにどれくらい待つ必要がありますか?**

最初の検出には最大 15 分、その後アラートが表示されるまで最大 5 分待ちます。これはアラートごとに異なります。

**コンソール エージェントなしで直接モードを使用すると、 ONTAPのアラートが表示されないのはなぜですか?*

NetAppアラートは、オンプレミスの標準コンソール エージェントを使用する場合にのみ利用できます。直接モードを使用すると、クラスターは監視されず、アラートも表示されません。

**アラート リスト ページから一部のアラートが消えるのはなぜですか?**

アラート機能は、一部のアラートをアクティブ状態に維持し、カウンター条件が満たされるか、期間が経過するとアラートを閉じます。これはアラートごとに異なります。

すべてのアラートを表示するには、[ステータス] 列フィルターを選択し、[クローズ] オプションを選択します。



== 情報の表示

**どのデバイスの解像度が最適ですか?**  NetAppアラートに推奨されるデバイス解像度は 1920 x 1080 以上です。

**どのブラウザを使用すればよいですか?**どの最新ブラウザでも動作します。
