---
sidebar: sidebar 
permalink: concept-alerts.html 
keywords: netapp, ontap, alert, capacity, performance, availability, security, protection, bluexp, NetApp Console alerts 
summary: NetApp ONTAP環境における容量、パフォーマンス、可用性、セキュリティに関連する問題または潜在的なリスクを表示します。  ONTAP System Manager を使用して詳細をドリルダウンできます。 
---
= ONTAPアラートについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppコンソールを使用して、 NetAppオンプレミスONTAPシステムの問題または潜在的なリスクを表示します。  ONTAP System Manager を使用して詳細をドリルダウンできます。



== NetAppコンソール

NetAppコンソールでONTAPアラートを表示します。

NetAppコンソールは、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとデータ サービスの集中管理を提供します。NetAppデータ サービスにアクセスして使用するには、コンソールが必要です。管理インターフェースとして、1 つのインターフェースから多数のストレージ リソースを管理できます。コンソール管理者は、企業内のすべてのシステムのストレージとサービスへのアクセスを制御できます。

NetAppコンソールの使用を開始するためにライセンスやサブスクリプションは必要ありません。ストレージ システムまたはNetAppデータ サービスへの接続を確保するためにクラウドにコンソール エージェントを展開する必要がある場合にのみ料金が発生します。ただし、コンソールからアクセスできる一部のNetAppデータ サービスは、ライセンスまたはサブスクリプションベースです。

詳細はこちら https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetAppコンソール"]。



== ONTAPアラートでできること

ONTAPアラートを表示して、 ONTAPストレージ システムのリスクや潜在的なリスクについての最新情報を入手します。 EMS 以外のアラートと EMS アラートがいくつか表示されます。次の重大度と影響領域に関する情報を確認できます。

* *重大度*: 重大、警告、情報
* *影響領域*: 容量、パフォーマンス、保護、可用性、セキュリティ、構成



TIP: NetAppコンソール UI の右上にある [通知] オプションは、 NetAppコンソールが実行している操作のステータスを監視し、対処が必要な問題を特定するのに役立ちます。これらの通知を電子メールで受け取ることができます。通知オプションには、 ONTAPアラートからのアラートは含まれません。



== ONTAPアラートを監視するメリット

ONTAPアラートを監視すると、次のような利点があります。

* クラスター全体のONTAPストレージに関するアラートを取得します。
* 他のサービスで使用するのと同じNetAppコンソール UI でアラートを表示します。
* ONTAPクラスターのアラートを詳しく調べるには、 NetAppコンソールから開始し、 ONTAP System Manager で詳細を確認します。




== 料金

NetApp ONTAPライセンスを使用すると、 ONTAPアラートを表示できます。



== ライセンス

ONTAPアラートを表示するには、 NetApp ONTAP 9.10 以上のライセンスが必要です。

試用ライセンスは必要ありません。

ONTAPアラートは、 NetAppコンソールの標準 (パブリック) モードでのみ表示できます。



== ONTAPアラートの仕組み

ONTAPアラートは、 NetAppコンソールのコア コンポーネントです。  ONTAPアラートはONTAPクラスターを監視し、 ONTAPからアラート データを受信します。

ONTAPアラートは、 NetAppコンソール SaaS 環境でのみ使用できます。ローカル コンソール エージェント UI では使用できません。



== サポートされているシステムとデータソース

ONTAPアラートを使用して、次のシステムおよびデータ ソースの問題を確認します。

*サポートされているシステム*

オンプレミスのONTAP NAS または SAN システムがサポートされています。

現時点では、Cloud Volumes ONTAPシステムはサポートされていません。

*サポートされているデータソース*

ONTAPで発生する特定のイベントに関するアラートを表示します。これらは、EMS とメトリックベースのアラートの組み合わせです。
